FROM php:7.1-apache

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

COPY start-apache /usr/local/bin

#mod_rewrite plugin to be enabled

RUN a2enmod rewrite

COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www

RUN apt-get update 

CMD ["start-apache"]